apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: app
spec:
  name: app
  owner: app
  cluster:
    name: cluster-pg-cron
  extensions:
    - name: pg_cron
      ensure: present
      version: "1.6"
    - name: pg_partman
      ensure: present
      version: "5.4"